### ISSUE TITLE
Inconsistent line ending intruduced

### ISSUE THREAD

**Issue by rcollette** [Kagami/gulp-ng-annotate#20]
It appears that gulp-ng-annotate is introducing an inconsistent line ending, which winds up throwing up a warning in Visual Studio.

![lineending](https://cloud.githubusercontent.com/assets/136476/5994251/e4f91524-aa39-11e4-97b8-71d89e157316.png)

**Comment by Kagami** [comment]
Please file that kind of issues to the ng-annotate's [bugtracker](https://github.com/olov/ng-annotate/issues). `gulp-ng-annotate` is just an wrapper around `ng-annotate`.
Thanks!
