### ISSUE TITLE
gulp-ng-annotate not working with node 0.12

### ISSUE THREAD

**Issue by Oza94** [Kagami/gulp-ng-annotate#24]
Hello,

I encountered an issue when I updated node to 0.12 version. Here is the error when I run my gulp task:

```
TypeError: Cannot assign to read only property '$methodName' of false
```

Regarding [this issue](https://github.com/olov/ng-annotate/issues/139) on the ng-annotate repo, this should be fixed by updating the version of ng-annotate used by gulp-ng-annotate.

**Comment by Kagami** [comment]
What version of `gulp-ng-annotate` are you using? Can you to run:
```bash
npm uninstall gulp-ng-annotate
npm install gulp-ng-annotate
```
and try once more? The minimal version of `ng-anotate` used by the latest `gulp-ng-annotae` is 0.15.4 and that bug was fixed in 0.15.1.

**Comment by Oza94** [comment]
I already did that once but npm still used the old version from my package.json. I removed the line from package.json, `npm install gulp-ng-annotate` and it works fine now, thanks for the quick reply!

**Comment by erperejildo** [comment]
After doing that I still having the error

**Comment by erperejildo** [comment]
Solved here by @dnlbox:
https://github.com/Swiip/generator-gulp-angular/issues/347
