### ISSUE TITLE
Workaround for sourcemap file property

### ISSUE THREAD

**Issue by Kagami** [Kagami/gulp-ng-annotate#26]
See: https://github.com/Kagami/gulp-ng-annotate/issues/9#issuecomment-65946516, https://github.com/Kagami/gulp-ng-annotate/issues/25#issuecomment-98439697, https://github.com/ivogabe/gulp-typescript/issues/44.

This most probably should be reported to upstream. If you have some problems with it or it breaks your sourcemap setup, feel free to comment.

**Comment by Francisc** [comment]
Hi,

I'm getting this error and am not sure what it means:
```
gulp-ng-annotate workaround for GH-26: change sourcemap `file` option from `endpoints.js` to `core/endpoints.js`
```

The part that is not clear is "change sourcemap `file` option from ... to ...". Huh? :)

**Comment by Kagami** [comment]
Some plugins (like gulp-typescript) set basename of the files instead of relative path in sourcemap object description, so it causes problems when merging them. See abovementioned links for additional details.

**Comment by Francisc** [comment]
I did look at the links, but all of them involved Typescript, so I didn't read further down.
I'm not using Typescript. I'm using BabelJS, maybe it's related.

**Comment by Kagami** [comment]
Probably BabelJS (or some other plugin in your pipeline) set basename instead of relative path too. Anyway, it's not an error, it's a warning just to note you and you can mute it with `gulpWarnings: false`.

**Comment by Francisc** [comment]
I'm not sure Babel has that configurable, I'll have to check.
The only issue with that warning is that sourcemaps are slightly wrong, some of the files are doubled.
Not a huge issue, but not perfect.

**Comment by Kagami** [comment]
>some of the files are doubled

I think it's caused by #25. Without fix that we're talking about you would probably get just wrong sourcemaps. There's currently no switch for that, but you can try to comment [these lines](https://github.com/Kagami/gulp-ng-annotate/blob/v1.1.0/index.js#L27-L32) in `node_modules/gulp_ng_annotate/index.js` and check the resulting sourcemaps.

**Comment by Francisc** [comment]
Thank you for your comments, Kagami. I appreciate it.
I'll take a look at this tomorrow and let you know.

**Comment by Francisc** [comment]
Commenting those out generates correct sourcemaps.
Although if it was that simple, you probably would have done it by now.

**Comment by Kagami** [comment]
Do you mean it has no duplicates, or you get same result? It would be good if you could provide some test repository with gulpfile, package.json and few test source files so I can reproduce it. Or at least show your gulpfile and approximate project structure.

**Comment by Francisc** [comment]
There are no duplicates and the directory structure is preserved.
Previously there were duplicates and directory structure was wrong.
For example, `endpoints.js` would show up in two places:
`./endpoints.js` as well as `./core/endpoints.js`.
The second is correct.

I'll try to reproduce this as soon as I can.

**Comment by sthames42** [comment]
What does this message mean? Where is the "sourcemap `file` option"?

**Comment by Kagami** [comment]
@sthames42, see links in description.
@vitalybe, what do you think, do we still need this? I think your case should be reported to typescript/gulp-typescript instead. Seems like workaround in gulp-ng-annotate for irrelevant issue causes confusion.

**Comment by sthames42** [comment]
I did but it hasn't helped. What do I need to pass to gulp-ng-annotate to set the sourcemap 'file' property? Currently, I am passing nothing related to sourcemaps.

**Comment by sthames42** [comment]
Here is the code for this problem, if it helps:

    var templates = streams.readArray(module.templates)
    .pipe(minifyInline(OPTS_MINIFY_INLINE))
    .pipe(  minifyHTML(OPTS_MINIFY_HTML))
    .pipe( ngTemplates("templates.js", Object.assign({ module: module.name, transformUrl: function(url) { return path.basename(url); }}, OPTS_NG_TEMPLATES)));
    
    var script  = module.scripts.shift();
    var script1 = merge2(streams.readArray([script]), templates).pipe(concat(script.relative));
    
    var scripts = merge2(script1, streams.readArray(module.scripts)).pipe(debug())
    .pipe(streams.through(function(file) { this.push(file); mainStream.push(file); }))
    .pipe(ngAnnotate(OPTS_NG_ANNOTATE))
    .pipe(    uglify(OPTS_UGLIFY));

And here is the message:
    `gulp-ng-annotate workaround for GH-26: change sourcemap 'file' option from 'templates.js' to 'ui/dateRangeSelector/dateRangeSelector.js'; if it breaks your sourcemap setup, please comment at https://github.com/Kagami/gulp-ng-annotate/issues/26 (you can mute this warning with 'gulpWarnings: false' option)`

**Comment by sthames42** [comment]
Ok, you can ignore this one. 'gulp-angular-templatecache' is generating a sourcemap and this is being passed through.
My bad.
Cheers!

**Comment by Kagami** [comment]
Removed in gulp-ng-annotate 2.0
