### ISSUE TITLE
bump dependency for ng-annotate

### ISSUE THREAD

**Issue by wayneseymour** [Kagami/gulp-ng-annotate#28]
ng-annotate@1.0.1 is latest as of ~17 hours ago.
Would you mind bumping to this latest release?

**Comment by jgrund** [comment]
+100 :100:

**Comment by Kagami** [comment]
`gulp-ng-annotate` uses semver. Just type `npm uninstall gulp-ng-annotate && npm install gulp-ng-annotate` and you will get the latest version of `ng-annotate`. There is no reason to bump version of `ng-annotate` in `gulp-ng-annotate` on every minor/patch update.

**Comment by wayneseymour** [comment]
Hrm, I'll try your idea.  Thanks.

**Comment by wayneseymour** [comment]
Ok, it seems to have worked.  Cool.
