### ISSUE TITLE
Bump ng-annotate version to 1.0.3 when it's released

### ISSUE THREAD

**Issue by philBrown** [Kagami/gulp-ng-annotate#34]
Hi

The next version of ng-annotate *should* contain a fix for https://github.com/olov/ng-annotate/issues/200. Could you please bump the dependency version when it is fixed?

Cheers

**Comment by Kagami** [comment]
Just reinstall `gulp-ng-annotate` after new version of `ng-annotate` will be released.

**Comment by philBrown** [comment]
Ah ok, thanks. Wasn't sure how one goes about updating sub-dependencies.
