### ISSUE TITLE
Change license to one that doesn't force the derivate work to be public domain

### ISSUE THREAD

**Issue by gabrielizaias** [Kagami/gulp-ng-annotate#36]
The current license says

> (...) a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, **including all related and neighboring rights**, to the extent allowed by law

Right now I'm working on a commercial project that requires the source to be private. I believe a lot of projects have this requirement and the `CC0 1.0` license ties ours hands.

I suggest changing to the MIT License: https://opensource.org/licenses/MIT

**Comment by Kagami** [comment]
It's applied only to the `gulp-ng-annotate` code itself, you can use with any project, including commercial. In fact, CC0 is even more permessive than MIT, you may consider it as public domain.
