### ISSUE TITLE
Dot notated namespacing

### ISSUE THREAD

**Issue by shannonhochkins** [Kagami/gulp-ng-annotate#37]
It would

Let's say I have a simple API called:
```javascript
var app = angular.module('slots', []);
app.service('slots.api', function() {
   return {
      get : function() {
         return true;
      }
   }
});

```
I use ng-annotate in conjunction with gulp to automatically include my dependencies for minification.

However, I have recently changed the way I namespace my modules, so If I have a service that's specifically relating to the the slots module, I'll prefix it with slots.

However ng-annotate doesn't look like it supports that, is there a way to automatically do this with ng-annotate? so that the result would look something like:

```javascript
app.service(['slots.api', function(api) {
    var result = api.get();
}]);
```

**Comment by Kagami** [comment]
Hi. Please report such issues to [ng-annotate's bugtracker](https://github.com/olov/ng-annotate/issues).
