### ISSUE TITLE
Error in plugin 'gulp-ng-annotate': error: couldn't process source due to parse error

### ISSUE THREAD

**Issue by dmitriz** [Kagami/gulp-ng-annotate#4]
Got this stange error on this harmless code:

$('#input-region').focusout(
  $scope.$apply();
);

events.js:72
        throw er; // Unhandled 'error' event
              ^
[gulp] Error in plugin 'gulp-ng-annotate': error: couldn't process source due to parse error
Line 54: Unexpected token ;
    at Transform._transform (/Users/dmitrizaitsev/Dropbox/33hotels/node_modules/gulp-ng-annotate/index.js:23:26)
    at Transform._read (/Users/dmitrizaitsev/Dropbox/33hotels/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/dmitrizaitsev/Dropbox/33hotels/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/dmitrizaitsev/Dropbox/33hotels/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:238:10)
    at writeOrBuffer (/Users/dmitrizaitsev/Dropbox/33hotels/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:228:5)
    at Transform.Writable.write (/Users/dmitrizaitsev/Dropbox/33hotels/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:195:11)
    at write (/Users/dmitrizaitsev/Dropbox/33hotels/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:605:24)
    at flow (/Users/dmitrizaitsev/Dropbox/33hotels/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:614:7)
    at Transform.pipeOnReadable (/Users/dmitrizaitsev/Dropbox/33hotels/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:646:5)
    at Transform.emit (events.js:92:17)

No error as soon as I remove ; after $scope.$apply();

**Comment by rizamasta** [comment]
but I did'nt understand..

**Comment by PerfectCarl** [comment]
I have the issue too: the error message is really misdirecting

**Comment by Kagami** [comment]
What's wrong with this error message? It says you have invalid code in `js/app.js` at line 53582. Also check out [FAQ](https://github.com/Kagami/gulp-ng-annotate#faq).

**Comment by PerfectCarl** [comment]
My [js/app.js](https://github.com/zhukov/webogram/blob/master/app/js/app.js) is only 40 lines long :)

**Comment by Kagami** [comment]
Probably your gulp build setup concatenated a lot of source code into vinyl File object with the path `js/app.js`. Try to add e.g. `gulp-tap` plugin before the `gulp-ng-annotate` and check the files and their contents which get passed to the `gulp-ng-annotate` input.

**Comment by PerfectCarl** [comment]
Thanks for your help! 

I don't know how to use `gulp-tap`
Maybe there is a way to disable the minification in the gulp task : 
```
gulp.task('usemin', ['templates', 'enable-production'], function() {
  return gulp.src(['app/index.html', 'app/badbrowser.html'])
    .pipe($.usemin({
      html: [$.minifyHtml({empty: true})],
      js: ['concat', $.ngAnnotate(), $.uglify({outSourceMap: false})],
      css: ['concat', $.minifyCss({compatibility: true, keepBreaks: true})]
    }))
    .pipe(gulp.dest('dist'));
});
```
> This is my first time with angular and gulp (I'm trying to fix errors in an existing application)

**Comment by Kagami** [comment]
Try to remove `$.ngAnnotate(), $.uglify({outSourceMap: false})` from the `js` target and check the resulting JS file at line 53582. I've never used `gulp-usemin` plugin though.

**Comment by PerfectCarl** [comment]
I've done what you adviced and I don't have the error anymore.

```
gulp.task('usemin', ['templates', 'enable-production'], function() {
  return gulp.src(['app/index.html', 'app/badbrowser.html'])  
    .pipe($.usemin({
      html: [$.minifyHtml({empty: true})],
      js: ['concat'],
      css: ['concat', $.minifyCss({compatibility: true, keepBreaks: true})]
    }))
    .pipe(gulp.dest('dist'));
});
```

Now if I add `ng-annotate` without the `uglify`, the faulty line the one marked below:
```js
$templateCache.put("partials/mobile/video_modal.html","<div class=\"media_modal_bottom_panel_wrap\">\n  <div class=\"media_modal_bottom_panel\">\n    <div class=\"media_modal_bottom_actions pull-right\">\n      <a class=\"media_modal_action_btn\" ng-if=\"messageID\" ng-click=\"delete()\" title=\"{{\'media_modal_delete\' | i18n}}\">\n        <i class=\"media_modal_action_btn_delete\"></i>\n      </a>\n    </div>\n\n    <div class=\"media_modal_bottom_actions pull-left\">\n      <a class=\"media_modal_action_btn\" ng-if=\"messageID\" ng-click=\"forward()\"  title=\"{{\'media_modal_forward\' | i18n}}\">\n        <i class=\"media_modal_action_btn_forward\"></i>\n      </a>\n    </div>\n\n    <div class=\"media_modal_info_wrap\">\n      <a class=\"media_modal_author\" my-user-link=\"video.user_id\" user-watch=\"true\"></a>\n      <br/>\n      <span class=\"media_modal_date\" ng-bind=\"video.date | dateOrTime :true\"></span>\n    </div>\n\n  </div>\n</div>\n\n<div class=\"media_modal_top_panel_wrap\">\n  <div class=\"media_modal_top_panel\">\n    <div class=\"media_modal_top_actions pull-right\">\n      <a class=\"media_modal_action_btn\" ng-click=\"download()\" title=\"{{\'media_modal_download\' | i18n}}\">\n        <i class=\"media_modal_action_btn_download\"></i>\n      </a>\n    </div>\n    <div class=\"media_modal_top_actions pull-left\">\n      <a ng-click=\"$close()\" class=\"navbar-quick-media-back\">\n        <i class=\"icon icon-back\"></i>\n        <div class=\"navbar-quick-back-title\">\n          <h4 class=\"media_modal_title_wrap\" my-i18n=\"media_modal_video\"></h4>\n        </div>\n      </a>\n    </div>\n  </div>\n</div>\n\n<div class=\"modal-dialog\">\n  <div class=\"modal-content\">\n    <div my-modal-width=\"{{video.full.width}}\" class=\"media_modal_wrap video_modal_wrap\" my-vertical-position=\"0.5\">\n\n      <div class=\"modal-body\">\n\n        <div class=\"video_modal_image_wrap\" my-load-video video=\"video\"></div>\n\n      </div>\n\n    </div>\n  </div>\n</div>\n\n");
// FAULTY LINE
$templateCache.put("partials/mobile/welcome.html","");}]);video_modal_wrap\" my-vertical-position=\"0.5\">\n\n      <div class=\"modal-body\">\n\n        <div class=\"video_modal_image_wrap\" my-load-video video=\"video\"></div>\n\n      </div>\n\n    </div>\n  </div>\n</div>\n\n");
$templateCache.put("partials/mobile/welcome.html","");}]);
/*!
 * Webogram v0.4.2 - messaging web application for MTProto
 * https://github.com/zhukov/webogram
 * Copyright (C) 2014 Igor Zhukov <igor.beatle@gmail.com>
 * https://github.com/zhukov/webogram/blob/master/LICENSE
 */

'use strict';

/* EmojiHelper */

(function (global, emojis, categories, spritesheets) {

**Comment by Kagami** [comment]
Looks like `gulp-angular-templatecache` artifacts or some other odd build error. Anyway, that's clearly a problem with your gulp build setup.

**Comment by PerfectCarl** [comment]
thanks!

**Comment by lfreneda** [comment]
love you guys, save me a lot of time D:  incorrent JS syntax in my javascript D:

**Comment by adam-marshall** [comment]
Just in case it helps anyone, I had a massive HTML file that was included in the project so was being concatenated in, and this was also causing the same error, as it seemed the file was too big.
