### ISSUE TITLE
Plug-in ngDialog DI is invalid

### ISSUE THREAD

**Issue by woleicom** [Kagami/gulp-ng-annotate#41]
Plug-in ngDialog DI is invalid
js:
`angular.module('orderList', [])
	.controller('orderCtrl', function($scope,ngDialog) {
		$scope.addAdrress = function() {
			ngDialog.open({
				template: 'add.html',
				className: 'ngdialog-theme-dadao',
				controller: function($scope) {
					console.log(1)
				},
				scope: $scope
			});
		}
	});`
build:
`angular.module("orderList", []).controller("orderCtrl", ["$scope", "ngDialog", function (o, e) {
    o.addAdrress = function () {
        e.open({
            template: "add.html", className: "ngdialog-theme-dadao", controller: function (o) {
                console.log(1)
            }, scope: o
        })
    }
}]);`

gulp：
`gulp.task('demo:js', function () {
    return gulp.src(['demo.js'])
        .pipe(ngAnnotate())
        .pipe(gulp.dest('./'));
});`
Is excuse me the mistake I configuration？

**Comment by Kagami** [comment]
Please open issue [here](https://github.com/olov/ng-annotate/issues).
