### ISSUE TITLE
 parse error 'import' and 'export' may appear only with 'sourceType: module' (1:0)

### ISSUE THREAD

**Issue by spoddutu** [Kagami/gulp-ng-annotate#44]
Error in plugin 'gulp-ng-annotate'
Message:
    visitor\carousel\carousel.js: error: couldn't process source due to parse error
'import' and 'export' may appear only with 'sourceType: module' (1:0)

**Comment by Kagami** [comment]
`ng-annotate` can't parse your source. I guess you need to transpile it.
