### ISSUE TITLE
parse error gulp-ng-annotate

### ISSUE THREAD

**Issue by SunilRumbaLama** [Kagami/gulp-ng-annotate#45]
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: styles\main.css: error: couldn't process source due to parse error
Unexpected character '@' (1:0).

**Comment by Kagami** [comment]
See https://github.com/Kagami/gulp-ng-annotate#i-got-an-error-error-in-plugin-gulp-ng-annotate-error-couldnt-process-source-due-to-parse-error
