### ISSUE TITLE
Critical Vulnerability on minimist package

### ISSUE THREAD

**Issue by LundDev23** [Kagami/gulp-ng-annotate#48]
Hi All,

I am using the latest  gulp-ng-annotate@2.1.0 package. When auditing the packages I noticed that there's a critical issue with minimist package. Any idea what we can do about this since it is a peer dependency of the ng-annotate package.

+-- gulp-ng-annotate@2.1.0
| `-- ng-annotate@1.2.2
|   `-- optimist@0.6.1
|     `-- minimist@0.0.10

**Comment by Kagami** [comment]
It's from another package https://github.com/olov/ng-annotate/blob/master/package.json#L14
But it's deprecated.
And https://www.npmjs.com/package/optimist is deprecated too.

So seems like no other way than forking and fixing by yourself if you need it.
